### ISSUE TITLE
 it doesn't work under python 3.6 and Mac OS X 10.12.

### ISSUE THREAD

**Issue by arcstep** [lepture/captcha#33]
I got some error when I install captcha in my mac.

```
>>> import captcha.image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/captcha/image.py", line 11, in <module>
    from PIL import Image
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so, 2): Symbol not found: _clock_gettime
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/.dylibs/liblzma.5.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/.dylibs/liblzma.5.dylib
```

You can see that it doesn't work under python 3.6 and Mac OS X 10.12.

so I **change pillow from 5.1.0 to 5.0.0**, it's all fine now ! :)

```
$ pip install pillow==5.0.0
...
Installing collected packages: pillow
  Found existing installation: Pillow 5.1.0
    Uninstalling Pillow-5.1.0:
      Successfully uninstalled Pillow-5.1.0
Successfully installed pillow-5.0.0
```

Perhaps many people will happen this error because they like to choose the newest version of every packages, so I must report above message : )

**Comment by lepture** [comment]
Not related to captcha. You can report it to Pillow instead.

**Comment by ndonkoHenri** [comment]
I just had this same issue. I will try changing my pillow version.
