### ISSUE TITLE
it doesn't work under (ubuntu18.04 captcha 0.3 pillow 6.0.0 python 3.6.7)

### ISSUE THREAD

**Issue by Icemelon99** [lepture/captcha#39]
I am a fresh coder, I am already find it from google, but...
this is my question, how can i solve it?
code:
```
    image = ImageCaptcha(fonts=['./ihome/utils/captcha/fonts/actionj.ttf', './ihome/utils/captcha/fonts/Georgia.ttf'])
    str1 = 'abcd123efghijk45lmn6opqrst789uvwxyz0'
    text = ''
    for i in range(0, 4):
        text += str1[random.randrange(0, len(str1))]
    image_data = image.generate(text)
```

ERROR:
Traceback (most recent call last):
  File "/home/icmelon/virtual_environment/flask/flask/lib/python3.6/site-packages/PIL/ImageFile.py", line 488, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/icmelon/virtual_environment/flask/flask/lib/python3.6/site-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/icmelon/virtual_environment/flask/flask/lib/python3.6/site-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/home/icmelon/virtual_environment/flask/flask/lib/python3.6/site-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/icmelon/virtual_environment/flask/flask/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/icmelon/virtual_environment/flask/flask/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/icmelon/virtual_environment/flask/flask/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/icmelon/virtual_environment/flask/flask/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/icmelon/virtual_environment/flask/flask/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/icmelon/virtual_environment/flask/flask/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/icmelon/virtual_environment/flask/flask/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/icmelon/virtual_environment/flask/flask/bin/ihome_project/ihome/api_1_0/verify_code.py", line 21, in get_image_codes
    image_data = image.generate(text)
  File "/home/icmelon/virtual_environment/flask/flask/lib/python3.6/site-packages/captcha/image.py", line 47, in generate
    im.save(out, format=format)
  File "/home/icmelon/virtual_environment/flask/flask/lib/python3.6/site-packages/PIL/Image.py", line 2007, in save
    save_handler(self, fp, filename)
  File "/home/icmelon/virtual_environment/flask/flask/lib/python3.6/site-packages/PIL/PngImagePlugin.py", line 896, in _save
    [("zip", (0, 0)+im.size, 0, rawmode)])
  File "/home/icmelon/virtual_environment/flask/flask/lib/python3.6/site-packages/PIL/ImageFile.py", line 502, in _save
    l, s, d = e
TypeError: 'ImagingEncoder' object is not iterable

**But pillow 5.0.0 can work!**

**Comment by ndonkoHenri** [comment]
Somewhat related to https://github.com/lepture/captcha/issues/33.
Seems like higher Pillow versions(>5.0.0) are not compatible to captcha.

**Comment by lepture** [comment]
0.5.0 works with Pillow 10.0.0

**Comment by ndonkoHenri** [comment]
Ok. Will try.
