### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer on Python 3.10.0

### ISSUE THREAD

**Issue by BennyThink** [lepture/captcha#51]
~ # python3
Python 3.10.0 (default, Nov 13 2021, 03:23:03) [GCC 10.3.1 20210424] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from captcha.image import ImageCaptcha
>>>
>>> image = ImageCaptcha()
>>> data = image.generate("chars")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/captcha/image.py", line 45, in generate
    im = self.generate_image(chars)
  File "/usr/local/lib/python3.10/site-packages/captcha/image.py", line 228, in generate_image
    im = self.create_captcha_image(chars, color, background)
  File "/usr/local/lib/python3.10/site-packages/captcha/image.py", line 212, in create_captcha_image
    mask = im.convert('L').point(table)
  File "/usr/local/lib/python3.10/site-packages/PIL/Image.py", line 1680, in point
    return self._new(self.im.point(lut, mode))
TypeError: 'float' object cannot be interpreted as an integer
>>>

~ # pip list
Package    Version
---------- -------
captcha    0.3
Pillow     8.4.0
pip        21.2.4
setuptools 57.5.0
wheel      0.37.0

**Comment by klkvr** [comment]
Fixed by #52

**Comment by coder2020official** [comment]
Is this still valid?
