### ISSUE TITLE
force_text deprecated in Django 4

### ISSUE THREAD

**Issue by enzedonline** [lepture/captcha#55]
Hi,

I'm getting my site ready to upgrade to Django 4, and hitting the following error when migrating:

```
$ python manage.py migrate
Traceback (most recent call last):
  File "<directory>\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "<directory>\.venv\lib\site-packages\django\core\management\__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "<directory>\.venv\lib\site-packages\django\core\management\__init__.py", line 401, in execute        
    django.setup()
  File "<directory>\.venv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "<directory>\.venv\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "<directory>\.venv\lib\site-packages\django\apps\config.py", line 300, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<directory>\home\models.py", line 2, in <module>
    from core.models import SEOPage
  File "<directory>\core\models.py", line 8, in <module>
    from wagtailcaptcha.models import WagtailCaptchaEmailForm
  File "<directory>\.venv\lib\site-packages\wagtailcaptcha\models.py", line 4, in <module>
    from .forms import WagtailCaptchaFormBuilder, remove_captcha_field
  File "<directory>\.venv\lib\site-packages\wagtailcaptcha\forms.py", line 4, in <module>
    from captcha.fields import ReCaptchaField
  File "<directory>\.venv\lib\site-packages\captcha\fields.py", line 11, in <module>
    from django.utils.encoding import force_text
ImportError: cannot import name 'force_text' from 'django.utils.encoding' (<directory>\.venv\lib\site-packages\django\utils\encoding.py)
```
Versions: 
captcha 0.3
wagtail-django-recaptcha 1.0
wagtail 2.16

Seems there is a library in fields.py that needs updating before the upgrade - is there any plan to make this package compatible with Django 4? It's the only thing blocking my upgrade at this stage.

**Comment by ivgenib** [comment]
The issue is with the package django-simple-captcha, which are installed in the same path as this package. Update to latest django-simple-captcha to resolve the issue.
