### ISSUE TITLE
TypeError: expected string

### ISSUE THREAD

**Issue by AmirHossein7090** [lepture/captcha#56]
I wrote the following code:

(Python 3.10.2)
```
def generate_captcha():
    captcha_text = ''.join(random.sample('1234567890', 4))
    image = ImageCaptcha(fonts=['captcha_fonts/Joseon-Regular.ttf'])
    data = image.generate(captcha_text)
    image.write(data, f'/captcha/{captcha_text}.png')
    return 1
```

but I got the following error:

___
expected string
Traceback (most recent call last):
  File "G:\Programming\Python Projects\FREELANCING\TelegramBot\venv\lib\site-packages\pyrogram\dispatcher.py", line 222, in handler_worker
    await handler.callback(self.client, *args)
  File "G:\Programming\Python Projects\FREELANCING\TelegramBot\bot.py", line 33, in start_handler
    data = generate_captcha()
  File "G:\Programming\Python Projects\FREELANCING\TelegramBot\bot.py", line 24, in generate_captcha
    image.write(data, f'/captcha/{captcha_text}.png')
  File "G:\Programming\Python Projects\FREELANCING\TelegramBot\venv\lib\site-packages\captcha\image.py", line 58, in write
    im = self.generate_image(chars)
  File "G:\Programming\Python Projects\FREELANCING\TelegramBot\venv\lib\site-packages\captcha\image.py", line 228, in generate_image
    im = self.create_captcha_image(chars, color, background)
  File "G:\Programming\Python Projects\FREELANCING\TelegramBot\venv\lib\site-packages\captcha\image.py", line 199, in create_captcha_image
    images.append(_draw_character(c))
  File "G:\Programming\Python Projects\FREELANCING\TelegramBot\venv\lib\site-packages\captcha\image.py", line 165, in _draw_character
    w, h = draw.textsize(c, font=font)
  File "G:\Programming\Python Projects\FREELANCING\TelegramBot\venv\lib\site-packages\PIL\ImageDraw.py", line 577, in textsize
    return self.multiline_textsize(
  File "G:\Programming\Python Projects\FREELANCING\TelegramBot\venv\lib\site-packages\PIL\ImageDraw.py", line 601, in multiline_textsize
    line_width, line_height = self.textsize(
  File "G:\Programming\Python Projects\FREELANCING\TelegramBot\venv\lib\site-packages\PIL\ImageDraw.py", line 583, in textsize
    return font.getsize(text, direction, features, language, stroke_width)
  File "G:\Programming\Python Projects\FREELANCING\TelegramBot\venv\lib\site-packages\PIL\ImageFont.py", line 421, in getsize
    size, offset = self.font.getsize(text, "L", direction, features, language)
TypeError: expected string

Process finished with exit code -1
___

I have read all the items from [this link](https://pypi.org/project/captcha/)!
What is the problem?

**Comment by AmirHossein7090** [comment]
This error was resolved by the following method :-)

```
def generate_captcha():
    captcha_text = ''.join(random.sample('1234567890', 4))
    image = ImageCaptcha()
    data = image.generate_image(captcha_text)
    data.show()
    data.save('test.png')
    # image.write(chars=data, output=f'/captcha/{captcha_text}')
    return 1
```
